development:
  adapter: postgresql
  database: email_callback_development
  username: postgres
  host: localhost
  port: 5432

test:
  adapter: postgresql
  database: email_callback_test
  username: postgres
  host: localhost
  port: 5432
