production:
  # from: your.email@gmail.com
  # delivery_method: smtp
  # address: smtp.gmail.com
  # port: 587
  # enable_starttls_auto: true
  # user_name: user
  # password: password
  # authentication: plain # plain, login, cram_md5, no auth by default
  # domain: localhost.localdomain # the HELO domain provided by the client to the server

development:
  # from:

test:
  from: test@foo.com
